post http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
###

get http://localhost:3001/api/auth

###
post http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test1",
  "password": "test1"
}